{{- range .Values.persistentVolumeClaims }}
{{- if .enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml (default (list "ReadWriteMany") .accessModes) | nindent 4 }}
  storageClassName: {{ .storageClass }}
  {{- with .volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
